apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: javawebapp-BUILD_NUMBER
        image: sujanadevops/javaappdemo:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
