apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-number
spec:
  replicas: 1
  selector:
    matchLabels:
          app: javawebapp
          version: "number"
  template:
    metadata:
      labels:
          app: javawebapp
          version: "number"
    spec:
      containers:
      - name: javawebapp-number
        image: sujanadevops/javaappdemo:${number}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  type: NodePort
  selector: 
    app: javawebapp
    version: "number"
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32450
